//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baymurzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Маршруты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Маршруты()
        {
            this.Рейсы = new HashSet<Рейсы>();
        }
    
        public int ID_маршрута { get; set; }
        public string Номер_маршрута { get; set; }
        public string Название { get; set; }
        public string Тип_сообщения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Рейсы> Рейсы { get; set; }
    }
}
