//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baymurzaev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Рейсы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Рейсы()
        {
            this.Транспорт = new HashSet<Транспорт>();
        }
    
        public int ID_рейса { get; set; }
        public int ID_маршрута { get; set; }
        public System.DateTime Дата_выхода { get; set; }
        public Nullable<System.TimeSpan> Время_старта { get; set; }
    
        public virtual Маршруты Маршруты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Транспорт> Транспорт { get; set; }
    }
}
